/* Generated by Cython 0.29.13 */

#ifndef __PYX_HAVE__call_obj
#define __PYX_HAVE__call_obj


#ifndef __PYX_HAVE_API__call_obj

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C float call_obj(PyObject *, std::vector<int> );

#endif /* !__PYX_HAVE_API__call_obj */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcall_obj(void);
#else
PyMODINIT_FUNC PyInit_call_obj(void);
#endif

#endif /* !__PYX_HAVE__call_obj */
